# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [143]:
import numpy as np
mat = np.full((4, 4), 7)
for i in range(4):
    mat[i][i] = i + 1
print(mat)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [144]:
mat2 = np.tile(np.arange(5), 5).reshape(5, 5)
print(mat2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [146]:
mat3 = np.random.random((10, 10))
mat3 = mat3 - mat3.mean(axis=1, keepdims=True)
#for row in mat3:
#    row_avg = np.mean(row)
#    for elem in mat3:
#         elem -= row_avg
print(mat3)

[[ 0.27242033  0.11513522  0.34026077 -0.2716525   0.03663868 -0.32337669
  -0.0919786   0.20661943 -0.09873039 -0.18533627]
 [-0.42673528 -0.15681366 -0.40137606  0.02586552  0.19464418  0.33614899
   0.08726049  0.36111839 -0.39798556  0.377873  ]
 [-0.11209424 -0.22255438  0.31079848 -0.20930724 -0.19282868  0.09739666
  -0.06357753  0.12433079  0.39233173 -0.1244956 ]
 [-0.44658057 -0.24031729  0.02499443  0.09952381 -0.11984313 -0.15694701
   0.2502938  -0.10804978  0.39104379  0.30588197]
 [ 0.15698347  0.32448118  0.23334758 -0.38347003 -0.41020074  0.22498348
  -0.45325005  0.31176537  0.29818116 -0.30282142]
 [-0.22285966 -0.35990321  0.09570663  0.25677446  0.33791763 -0.32119945
  -0.18637057  0.59858822 -0.166746   -0.03190803]
 [-0.29468229  0.45685851  0.01346117 -0.3157426  -0.14891234  0.24098943
  -0.05818827 -0.30109216  0.21692878  0.19037978]
 [-0.41703512 -0.21934336  0.45452769  0.29213055 -0.21699495  0.02798891
  -0.46261737  0.01961498  0.18335755  0.33837112]


4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [148]:
mat4 = np.random.random((10, 10))
for column in range(10):
    column_avg = np.median(mat4[:, column])
    for elem in mat4:
         elem -= column_avg
print(mat4)

[[-0.50760478  0.19632049  0.06339842  0.27101398 -0.19266621 -0.46655507
  -0.42842697 -0.47100395 -0.37451372  0.02854011]
 [ 0.15303789 -0.39514973 -0.54148991 -0.47483901 -0.3087756   0.17424959
  -0.08661282 -0.04536904 -0.34192628  0.18199805]
 [-0.25570206 -0.51791039 -0.28696556 -0.25453789  0.23943123  0.21907495
   0.23700894 -0.1439233   0.14179625 -0.32907679]
 [ 0.18243832  0.39558939  0.16339573 -0.43342357  0.15492995 -0.50509317
  -0.08347569 -0.39106719 -0.04677108  0.27399818]
 [-0.05361246  0.18385824 -0.30092989  0.16759943  0.33896543  0.13668449
  -0.2851296   0.11698153  0.35883088  0.25425692]
 [ 0.20682797 -0.50979699 -0.41175319 -0.24187552 -0.15866423  0.14766419
   0.17591142  0.08141066 -0.39935977 -0.32418583]
 [-0.36702497 -0.31074435 -0.11686148 -0.41316619  0.01957192 -0.42284569
   0.31184098  0.11247092  0.03990411 -0.02854011]
 [-0.41642693  0.34893874  0.03530837 -0.20939286 -0.01202543 -0.35313092
  -0.28869671 -0.1228399  -0.47969877 -0.37918465]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [85]:
mat5 = np.random.random((5, 5))
arr_max = np.amax(mat5, axis=1).reshape((5, 1))
arr_min = np.amin(mat5, axis=1).reshape((5, 1))
mat5 = np.append(mat5, arr_max, axis = 1)
mat5 = np.append(mat5, arr_min, axis = 1)
print(mat5)

[[0.26776077 0.49691614 0.81730874 0.18585001 0.66601796 0.81730874
  0.18585001]
 [0.97440552 0.37665434 0.42098957 0.95121537 0.47798782 0.97440552
  0.37665434]
 [0.66515028 0.33582524 0.28918483 0.82105848 0.58558998 0.82105848
  0.28918483]
 [0.1969076  0.16155761 0.09087046 0.13861895 0.46360777 0.46360777
  0.09087046]
 [0.38116767 0.40634379 0.09387175 0.16150009 0.03598701 0.40634379
  0.03598701]]


6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [111]:
arr = np.arange(1, 52)
arr_even = np.take(arr, np.arange(1, 51, 2)).reshape(5, 5) 
arr_odd = np.take(arr, np.arange(0, 50, 2)).reshape(5, 5)
arr_mult = np.multiply(arr_even, arr_odd)
print(arr_odd)
print(arr_even)
print(arr_mult)
print(np.linalg.det(arr_mult))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]
0.0


7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [149]:
mat6 = np.zeros((8,8), dtype=int)
mat6[1::2,::2] = 1
mat6[::2,1::2] = 1
print(mat6)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
