# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [143]:
import numpy as np
mat = np.full((4, 4), 7)
for i in range(4):
    mat[i][i] = i + 1
print(mat)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [144]:
mat2 = np.tile(np.arange(5), 5).reshape(5, 5)
print(mat2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [146]:
mat3 = np.random.random((10, 10))
mat3 = mat3 - mat3.mean(axis=1, keepdims=True)
#for row in mat3:
#    row_avg = np.mean(row)
#    for elem in mat3:
#         elem -= row_avg
print(mat3)

[[ 0.27242033  0.11513522  0.34026077 -0.2716525   0.03663868 -0.32337669
  -0.0919786   0.20661943 -0.09873039 -0.18533627]
 [-0.42673528 -0.15681366 -0.40137606  0.02586552  0.19464418  0.33614899
   0.08726049  0.36111839 -0.39798556  0.377873  ]
 [-0.11209424 -0.22255438  0.31079848 -0.20930724 -0.19282868  0.09739666
  -0.06357753  0.12433079  0.39233173 -0.1244956 ]
 [-0.44658057 -0.24031729  0.02499443  0.09952381 -0.11984313 -0.15694701
   0.2502938  -0.10804978  0.39104379  0.30588197]
 [ 0.15698347  0.32448118  0.23334758 -0.38347003 -0.41020074  0.22498348
  -0.45325005  0.31176537  0.29818116 -0.30282142]
 [-0.22285966 -0.35990321  0.09570663  0.25677446  0.33791763 -0.32119945
  -0.18637057  0.59858822 -0.166746   -0.03190803]
 [-0.29468229  0.45685851  0.01346117 -0.3157426  -0.14891234  0.24098943
  -0.05818827 -0.30109216  0.21692878  0.19037978]
 [-0.41703512 -0.21934336  0.45452769  0.29213055 -0.21699495  0.02798891
  -0.46261737  0.01961498  0.18335755  0.33837112]


4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [151]:
mat4 = np.random.random((10, 10))
for column in range(10):
    column_avg = np.median(mat4[:, column])
    for elem in mat4:
         elem -= column_avg
print(mat4)

[[ 0.01665227  0.22737251  0.12834248  0.45889487  0.02274806 -0.09314095
  -0.17509005 -0.45270539  0.45583423 -0.32920667]
 [ 0.02718681  0.4950972  -0.29441489  0.38606617 -0.39650105  0.01282843
   0.25665514  0.31380478 -0.40384121  0.16219102]
 [-0.17282935 -0.187956    0.39235536 -0.08990975 -0.03285074 -0.22691642
   0.32347235  0.49210232 -0.11714702  0.05432592]
 [-0.13028866  0.00834452 -0.4693459   0.30944688  0.13459052 -0.44443307
   0.43872017 -0.34532253  0.16374284 -0.35122767]
 [ 0.49313641  0.10495102  0.16395208 -0.3676115   0.30190044 -0.15734506
   0.12643617  0.20037664  0.35284058  0.09170875]
 [-0.31083455 -0.29774699  0.28514316 -0.38709583  0.36166179  0.13945336
   0.23887306  0.05486819  0.03835841 -0.21944817]
 [ 0.38399504 -0.2971427   0.32094518 -0.17154617  0.49429243  0.20026494
  -0.17423516 -0.08372118 -0.05397274 -0.18789887]
 [ 0.48488002 -0.07666352  0.11632862 -0.37248847 -0.1498381   0.21827601
   0.32692451 -0.38413403 -0.46014748  0.24675898]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [85]:
mat5 = np.random.random((5, 5))
arr_max = np.amax(mat5, axis=1).reshape((5, 1))
arr_min = np.amin(mat5, axis=1).reshape((5, 1))
mat5 = np.append(mat5, arr_max, axis = 1)
mat5 = np.append(mat5, arr_min, axis = 1)
print(mat5)

[[0.26776077 0.49691614 0.81730874 0.18585001 0.66601796 0.81730874
  0.18585001]
 [0.97440552 0.37665434 0.42098957 0.95121537 0.47798782 0.97440552
  0.37665434]
 [0.66515028 0.33582524 0.28918483 0.82105848 0.58558998 0.82105848
  0.28918483]
 [0.1969076  0.16155761 0.09087046 0.13861895 0.46360777 0.46360777
  0.09087046]
 [0.38116767 0.40634379 0.09387175 0.16150009 0.03598701 0.40634379
  0.03598701]]


6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [111]:
arr = np.arange(1, 52)
arr_even = np.take(arr, np.arange(1, 51, 2)).reshape(5, 5) 
arr_odd = np.take(arr, np.arange(0, 50, 2)).reshape(5, 5)
arr_mult = np.multiply(arr_even, arr_odd)
print(arr_odd)
print(arr_even)
print(arr_mult)
print(np.linalg.det(arr_mult))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]
0.0


7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [149]:
mat6 = np.zeros((8,8), dtype=int)
mat6[1::2,::2] = 1
mat6[::2,1::2] = 1
print(mat6)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
